Nightly Fail Inspector debug 2 (#119)
Added support for array of job/step names.
Debugged with tt-torch and tt-forge-fe.

diff --git a/.github/actions/fail-inspector-inspect/action.yml b/.github/actions/fail-inspector-inspect/action.yml
--- a/.github/actions/fail-inspector-inspect/action.yml
+++ b/.github/actions/fail-inspector-inspect/action.yml
@@ -112,13 +112,15 @@ runs:
         echo "Machines: $(cat machines.log)"
         while read -r machine; do
           for dir in log-a/test-log-"$machine"-*/; do
-            sed -n '/=========================== short test summary info ============================/,$p' "$dir/pytest.log" >temp.log
-            grep '^FAILED ' "temp.log" | sed 's/^FAILED //; s/^\(.*\) - .*/\1/; s/^\(.*\]\).*/\1/' >>a-"$machine".log
+            sed -n '/=========================== short test summary info ============================/,$p' "$dir/pytest.log" >temp.log || true
+            grep '^FAILED ' "temp.log" | sed 's/^FAILED //; s/^\(.*\) - .*/\1/; s/^\(.*\]\).*/\1/' >>a-"$machine".log || true
           done
           for dir in log-b/test-log-"$machine"-*/; do
-            sed -n '/=========================== short test summary info ============================/,$p' "$dir/pytest.log" >temp.log
-            grep '^FAILED ' "temp.log" | sed 's/^FAILED //; s/^\(.*\) - .*/\1/; s/^\(.*\]\).*/\1/' >>b-"$machine".log
+            sed -n '/=========================== short test summary info ============================/,$p' "$dir/pytest.log" >temp.log || true
+            grep '^FAILED ' "temp.log" | sed 's/^FAILED //; s/^\(.*\) - .*/\1/; s/^\(.*\]\).*/\1/' >>b-"$machine".log || true
           done
+          echo "----Current  Tests for machine $machine: $(cat b-"$machine".log)"
+          echo "----Previous Tests for machine $machine: $(cat b-"$machine".log)"
           # get only the lines that are in b.log but not in a.log
           if [ ! -s a-"$machine".log ]; then
             cp b-"$machine".log tests-"$machine".log
@@ -126,7 +128,7 @@ runs:
           if [ ! -s b-"$machine".log ]; then
             echo "List of failed tests for machine '$machine' is empty, nothing to do."
           else
-            grep -Fxv -f a-"$machine".log b-"$machine".log >tests-"$machine".log
+            grep -Fxv -f a-"$machine".log b-"$machine".log >tests-"$machine".log || true
             echo "----Tests for machine $machine: $(cat tests-"$machine".log)"
           fi
         done <machines.log
@@ -181,9 +183,18 @@ runs:
       env:
         GH_TOKEN: ${{ inputs.token }}
       run: |
-        repo="${{ input.repo }}"
-        test_job_names=("${{ inputs.test_job_names }}")
-        test_step_names=("${{ inputs.test_step_names }}")
+        repo="${{ inputs.repo }}"
+
+        if ! echo '${{ inputs.test_job_names }}' | jq empty; then
+          test_job_names=("${{ inputs.test_job_names }}")
+        else
+          mapfile -t test_job_names < <(echo '${{ inputs.test_job_names }}' | jq -r '.[]')
+        fi
+        if ! echo '${{ inputs.test_job_names }}' | jq empty; then
+          test_step_names=("${{ inputs.test_step_names }}")
+        else
+          mapfile -t test_step_names < <(echo '${{ inputs.test_step_names }}' | jq -r '.[]')
+        fi
 
         curr_wf_id="${{ steps.success-failed.outputs.curr_wf_id }}"
         curr_wf_attempt="${{ steps.success-failed.outputs.curr_wf_attempt }}"
@@ -214,7 +225,7 @@ runs:
               step_name=$(jq -r ".jobs[$i].steps[$j].name" workflow_jobs.json)
               step_conclusion=$(jq -r ".jobs[$i].steps[$j].conclusion" workflow_jobs.json)
               for test_step_name in "${test_step_names[@]}"; do
-                if [[ "$step_name" == $test_step_name ]]; then
+                if [[ "$step_name" == *"$test_step_name"* ]]; then
                   break 2
                 fi
               done
