Nightly Fail inspector debug (#122)
Fix for sanity: add repo for gh workflow acquisition and checks if
successful

diff --git a/.github/actions/fail-inspector-inspect/action.yml b/.github/actions/fail-inspector-inspect/action.yml
--- a/.github/actions/fail-inspector-inspect/action.yml
+++ b/.github/actions/fail-inspector-inspect/action.yml
@@ -4,7 +4,7 @@ description: |
   Fail inspector bisect nightly workflows searching for the first commit that broke the nightly build.
   This action will download the test log artifacts from the nightly workflow and run the inspector on them.
   Output is the matrix that runs tests.
-  Fail Inspector - Inspect is accompanied by Deduct action that will make decisions based on the results of matrix test run.
+  Fail Inspector - Inspect is accompanied by Test and Deduct actions that will perform tests and make decisions based on the results of matrix test run.
 
 inputs:
   repo:
@@ -21,10 +21,10 @@ inputs:
     description: 'Slack webhook URL'
     required: true
   test_job_names:
-    description: 'Test job names (space separated)'
+    description: 'Test job name or job names in json format eg. ["job1", "job2"]'
     required: true
   test_step_names:
-    description: 'Test step names (space separated)'
+    description: 'Test step name or step names in json format eg. ["step1", "step2"]'
     required: true
 
 outputs:
@@ -196,13 +196,19 @@ runs:
           mapfile -t test_step_names < <(echo '${{ inputs.test_step_names }}' | jq -r '.[]')
         fi
 
-        echo "----Workflow run JSON: $(cat workflow_jobs.json)"
-
         curr_wf_id="${{ steps.success-failed.outputs.curr_wf_id }}"
         curr_wf_attempt="${{ steps.success-failed.outputs.curr_wf_attempt }}"
         rm -f report.txt
 
-        gh run view $curr_wf_id --attempt $curr_wf_attempt --json jobs >workflow_jobs.json
+        if ! gh run view -R "$repo" $curr_wf_id --attempt $curr_wf_attempt --json jobs >workflow_jobs.json; then
+          echo "ERROR: Failed to fetch workflow jobs."
+          exit 1
+        fi
+
+        if ! jq empty workflow_jobs.json >/dev/null 2>&1; then
+          echo "ERROR: workflow_jobs.json is not valid JSON."
+          exit 1
+        fi
 
         # Iterate through jobs using index
         job_count=$(jq '.jobs | length' workflow_jobs.json)
