skip unzip

diff --git a/.github/actions/download-artifact/action.yaml b/.github/actions/download-artifact/action.yaml
--- a/.github/actions/download-artifact/action.yaml
+++ b/.github/actions/download-artifact/action.yaml
@@ -78,12 +78,14 @@ runs:
             return 1
           fi
 
-          unzip -o "$path/${ARTIFACT_NAME}.zip" -d "$path"
-          if [ $? -ne 0 ]; then
-            echo "Error: Failed to unzip artifact."
-            return 1
-          fi
-          rm "$path/${ARTIFACT_NAME}.zip"
+          ls -lah $path
+
+          # unzip -o "$path/${ARTIFACT_NAME}.zip" -d "$path"
+          # if [ $? -ne 0 ]; then
+          #   echo "Error: Failed to unzip artifact."
+          #   return 1
+          # fi
+          # rm "$path/${ARTIFACT_NAME}.zip"
 
           # Check if we need to untar
           for file in "$path"/*.tar*; do
