add skip wheel install fact (#185)
We want to only skip the tt-forge wheel install test for now. I have
added a release fact `skip_wheel_install` boolean to control this
behavior for easy future adjustment.

Fixes
https://github.com/tenstorrent/tt-forge/actions/runs/15860335527/job/44715803236#step:3:329


```bash
The conflict is caused by:
    pjrt-plugin-tt 0.1.0.dev20250624 depends on jax>=0.6.0
    tt-forge-fe 0.1.0.dev20250624 depends on jax==0.4.30
```

diff --git a/.github/actions/tt-forge-wheel/action.yml b/.github/actions/tt-forge-wheel/action.yml
--- a/.github/actions/tt-forge-wheel/action.yml
+++ b/.github/actions/tt-forge-wheel/action.yml
@@ -58,4 +58,8 @@ runs:
         mv ${{ github.workspace }}/dist/*.whl ${{ github.workspace }}/release/artifacts/.
         cd ${{ github.workspace }}/release/artifacts
         # TODO: build alerting around this.
-        pip install *.whl || echo "Failed to install wheel"
+        if [ "${{ steps.set-release-facts.outputs.skip_wheel_install }}" == "false" ]; then
+          pip install *.whl
+        else
+          pip install *.whl || echo "Failed to install wheel"
+        fi
