Enable device perf

diff --git a/.github/workflows/perf-benchmark.yml b/.github/workflows/perf-benchmark.yml
--- a/.github/workflows/perf-benchmark.yml
+++ b/.github/workflows/perf-benchmark.yml
@@ -7,7 +7,7 @@ on:
         description: "Docker image used in tests"
         required: false
         type: string
-        default: "ghcr.io/tenstorrent/tt-forge/tt-forge-slim:latest"
+        default: "ghcr.io/tenstorrent/tt-forge/tt-forge-slim:dev20250701"
   workflow_call:
     inputs:
       docker-image:
@@ -38,6 +38,7 @@ jobs:
         - /etc/udev/rules.d:/etc/udev/rules.d
         - /lib/modules:/lib/modules
         - /opt/tt_metal_infra/provisioning/provisioning_env:/opt/tt_metal_infra/provisioning/provisioning_env
+        - /usr/local/bin:/usr/local/bin
         - /mnt/dockercache:/mnt/dockercache
 
     # tt-torch reqs are not needed by tt-torch, but rather by benchmarking infra, should be moved elsewhere: https://github.com/tenstorrent/tt-forge/issues/177
@@ -45,21 +46,21 @@ jobs:
       fail-fast: false
       matrix:
         build: [
-          { runs-on: "n150", project: "tt-forge-fe", name: "llama",             dir: "LlamaModel",                   bs: 1,  lp: 32, df: 'float32',  ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "mnist_linear",      dir: "MNISTLinear",                  bs: 32, lp: 32, df: 'float32',  ts: 'na', },
-          { runs-on: "n150", project: "tt-forge-fe", name: "resnet_hf",         dir: "ResNetForImageClassification", bs: 8,  lp: 32, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "mobilenetv2_basic", dir: "MobileNetv2Basic",             bs: 8,  lp: 32, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "efficientnet_timm", dir: "EfficientNetTimmB0",           bs: 6,  lp: 32, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "segformer",         dir: "Segformer",                    bs: 1,  lp: 32, df: 'float32',  ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "vit",               dir: "ViTBase",                      bs: 8,  lp: 32, df: 'float32',  ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "vovnet",            dir: "VovnetOSMR",                   bs: 16, lp: 32, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v4",           dir: "YOLOv4",                       bs: 1,  lp: 32, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v8",           dir: "YOLOv8",                       bs: 1,  lp: 32, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v9",           dir: "YOLOv9",                       bs: 1,  lp: 32, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v10",          dir: "YOLOv10",                      bs: 1,  lp: 32, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-forge-fe", name: "unet",              dir: "UNet",                         bs: 1,  lp: 32, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-torch",    name: "resnet",            dir: "",                             bs: 8,  lp: 32, df: 'default',  ts: 'na', pyreq: "loguru requests transformers datasets torchvision pytest ultralytics", libreq: "libgl1-mesa-glx libglib2.0-0" },
-          { runs-on: "n150", project: "tt-xla",      name: "resnet",            dir: "",                             bs: 1,  lp: 32, df: 'default',  ts: 'na', pyreq: "pytest tqdm loguru requests transformers datasets flax torch" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "llama",             dir: "LlamaModel",                   bs: 1,  lp: 1, df: 'float32',  ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "mnist_linear",      dir: "MNISTLinear",                  bs: 32, lp: 1, df: 'float32',  ts: 'na', },
+          { runs-on: "n150", project: "tt-forge-fe", name: "resnet_hf",         dir: "ResNetForImageClassification", bs: 8,  lp: 1, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "mobilenetv2_basic", dir: "MobileNetv2Basic",             bs: 8,  lp: 1, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "efficientnet_timm", dir: "EfficientNetTimmB0",           bs: 6,  lp: 1, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "segformer",         dir: "Segformer",                    bs: 1,  lp: 1, df: 'float32',  ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "vit",               dir: "ViTBase",                      bs: 8,  lp: 1, df: 'float32',  ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "vovnet",            dir: "VovnetOSMR",                   bs: 16, lp: 1, df: 'bfloat16', ts: 'classification', libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v4",           dir: "YOLOv4",                       bs: 1,  lp: 1, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v8",           dir: "YOLOv8",                       bs: 1,  lp: 1, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v9",           dir: "YOLOv9",                       bs: 1,  lp: 1, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "yolo_v10",          dir: "YOLOv10",                      bs: 1,  lp: 1, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-forge-fe", name: "unet",              dir: "UNet",                         bs: 1,  lp: 1, df: 'bfloat16', ts: 'na',           libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-torch",    name: "resnet",            dir: "",                             bs: 8,  lp: 1, df: 'default',  ts: 'na', pyreq: "loguru requests transformers datasets torchvision pytest ultralytics", libreq: "libgl1-mesa-glx libglib2.0-0" },
+          { runs-on: "n150", project: "tt-xla",      name: "resnet",            dir: "",                             bs: 1,  lp: 1, df: 'default',  ts: 'na', pyreq: "pytest tqdm loguru requests transformers datasets flax torch" },
         ]
     runs-on:
       - ${{ matrix.build.runs-on }}
@@ -115,25 +116,25 @@ jobs:
     #   run: git config --global --add safe.directory ${{ steps.strings.outputs.work-dir }}
 
     # ttrt version (sha) should be taken from release metadata or something
-    # - name: Download ttrt wheel
-    #   uses: dawidd6/action-download-artifact@v6
-    #   with:
-    #     workflow_conclusion: success
-    #     workflow: on-push.yml
-    #     branch: main
-    #     name: "(ttrt-whl|install-artifacts)-tracy"
-    #     name_is_regexp: true
-    #     repo: tenstorrent/tt-mlir
-    #     check_artifacts: true
-    #     path: ./
+    - name: Download ttrt wheel
+      uses: dawidd6/action-download-artifact@v6
+      with:
+        workflow_conclusion: success
+        workflow: on-push.yml
+        branch: main
+        name: "(ttrt-whl|install-artifacts)-tracy"
+        name_is_regexp: true
+        repo: tenstorrent/tt-mlir
+        check_artifacts: true
+        path: ./
 
-    # - name: Untar ttmlir install directory
-    #   shell: bash
-    #   run: |
-    #     mv install-artifacts-tracy/ install/
-    #     cd install
-    #     tar xvf artifact.tar
-    #     cd ..
+    - name: Untar ttmlir install directory
+      shell: bash
+      run: |
+        mv install-artifacts-tracy/ install/
+        cd install
+        tar xvf artifact.tar
+        cd ..
 
     - name: Run Perf Benchmark
       shell: bash
@@ -144,26 +145,36 @@ jobs:
       run: |
         mkdir -p ${{ steps.strings.outputs.perf_report_path }}
         source /home/forge/venv-${{ matrix.build.project }}/bin/activate
+        echo "Run perf benchmark"
         python benchmark/benchmark.py -p ${{ matrix.build.project}} -m ${{ matrix.build.name }} -bs ${{ matrix.build.bs }} -df ${{ matrix.build.df }} -lp ${{ matrix.build.lp }} -ts ${{ matrix.build.ts }} -o ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json
+        echo "Remove system descriptor from ttir"
         if [ -n "${{ matrix.build.dir }}" ]; then
-          python benchmark/create_ttir.py ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir.mlir
+          python benchmark/device_perf.py -ct ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir.mlir
         fi
 
-    # - name: Install and run TTRT
-    #   if: ${{ matrix.build.project != 'tt-torch' }}
-    #   shell: bash
+    - name: Install and run TTRT
+      if: ${{ matrix.build.project != 'tt-torch' }}
+      shell: bash
+      run: |
+        python -m venv ttrt-venv
+        source ttrt-venv/bin/activate
+        apt-get install -y -qq --no-install-recommends libtbb12
+        apt-get install -y -qq --no-install-recommends libcapstone4
+        pip install ttrt-whl-tracy/ttrt*.whl --force-reinstall
+        pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
+        echo "save artifacts"
+        ttrt query --save-artifacts
+        if [ -z "${{ matrix.build.allow-fail }}" ]; then
+          ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json
+        else
+          ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_${{ steps.fetch-job-id.outputs.job_id }}.json || true
+        fi
+
+    # - name: Sleep to debug container
+    #   if: failure()
     #   run: |
-    #     python -m venv ttrt-venv
-    #     source ttrt-venv/bin/activate
-    #     pip install ttrt-whl-tracy/ttrt*.whl --force-reinstall
-    #     pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
-    #     echo "save artifacts"
-    #     ttrt query --save-artifacts
-    #     if [ -z "${{ matrix.build.allow-fail }}" ]; then
-    #       ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}.json # _${{ steps.fetch-job-id.outputs.job_id }}.json
-    #     else
-    #       ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_.json || true # ${{ steps.fetch-job-id.outputs.job_id }}.json || true
-    #     fi
+    #     echo "Sleeping for 1 hour to debug container"
+    #     sleep 3600
 
     - name: Upload Perf Report
       uses: actions/upload-artifact@v4
