remove ttrt, try jobid

diff --git a/.github/workflows/perf-benchmark.yml b/.github/workflows/perf-benchmark.yml
--- a/.github/workflows/perf-benchmark.yml
+++ b/.github/workflows/perf-benchmark.yml
@@ -34,12 +34,12 @@ jobs:
     name: "run-perf-benchmarks ${{matrix.build.project }}-${{matrix.build.name }} (${{ matrix.build.runs-on }}, ${{ matrix.build.bs }}, ${{ matrix.build.lp }})"
     steps:
 
-    # - name: Fetch job id
-    #   id: fetch-job-id
-    #   uses: tenstorrent/tt-github-actions/.github/actions/job_id@main
-    #   with:
-    #     gh_token: ${{ secrets.GITHUB_TOKEN }}
-    #     job_name: "run-perf-benchmarks ${{matrix.build.project }}-${{matrix.build.name }} (${{ matrix.build.runs-on }}, ${{ matrix.build.bs }}, ${{ matrix.build.lp }})"
+    - name: Fetch job id
+      id: fetch-job-id
+      uses: tenstorrent/tt-github-actions/.github/actions/job_id@main
+      with:
+        gh_token: ${{ secrets.GH_TOKEN }}
+        job_name: "run-perf-benchmarks ${{matrix.build.project }}-${{matrix.build.name }} (${{ matrix.build.runs-on }}, ${{ matrix.build.bs }}, ${{ matrix.build.lp }})"
 
     - name: Set reusable strings
       id: strings
@@ -90,25 +90,25 @@ jobs:
         fi
 
     # ttrt version (sha) should be taken from release metadata or something
-    - name: Download ttrt wheel
-      uses: dawidd6/action-download-artifact@v6
-      with:
-        workflow_conclusion: success
-        workflow: on-push.yml
-        branch: main
-        name: "(ttrt-whl|install-artifacts)-tracy"
-        name_is_regexp: true
-        repo: tenstorrent/tt-mlir
-        check_artifacts: true
-        path: ./
+    # - name: Download ttrt wheel
+    #   uses: dawidd6/action-download-artifact@v6
+    #   with:
+    #     workflow_conclusion: success
+    #     workflow: on-push.yml
+    #     branch: main
+    #     name: "(ttrt-whl|install-artifacts)-tracy"
+    #     name_is_regexp: true
+    #     repo: tenstorrent/tt-mlir
+    #     check_artifacts: true
+    #     path: ./
 
-    - name: Untar ttmlir install directory
-      shell: bash
-      run: |
-        mv install-artifacts-tracy/ install/
-        cd install
-        tar xvf artifact.tar
-        cd ..
+    # - name: Untar ttmlir install directory
+    #   shell: bash
+    #   run: |
+    #     mv install-artifacts-tracy/ install/
+    #     cd install
+    #     tar xvf artifact.tar
+    #     cd ..
 
     - name: Set up Python
       uses: actions/setup-python@v5
@@ -159,21 +159,21 @@ jobs:
           python benchmark/create_ttir.py ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir.mlir
         fi
 
-    - name: Install and run TTRT
-      if: ${{ matrix.build.project != 'tt-torch' }}
-      shell: bash
-      run: |
-        python -m venv ttrt-venv
-        source ttrt-venv/bin/activate
-        pip install ttrt-whl-tracy/ttrt*.whl --force-reinstall
-        pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
-        echo "save artifacts"
-        ttrt query --save-artifacts
-        if [ -z "${{ matrix.build.allow-fail }}" ]; then
-          ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}.json # _${{ steps.fetch-job-id.outputs.job_id }}.json
-        else
-          ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_.json || true # ${{ steps.fetch-job-id.outputs.job_id }}.json || true
-        fi
+    # - name: Install and run TTRT
+    #   if: ${{ matrix.build.project != 'tt-torch' }}
+    #   shell: bash
+    #   run: |
+    #     python -m venv ttrt-venv
+    #     source ttrt-venv/bin/activate
+    #     pip install ttrt-whl-tracy/ttrt*.whl --force-reinstall
+    #     pip install torch==2.3.0 --index-url https://download.pytorch.org/whl/cpu
+    #     echo "save artifacts"
+    #     ttrt query --save-artifacts
+    #     if [ -z "${{ matrix.build.allow-fail }}" ]; then
+    #       ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}.json # _${{ steps.fetch-job-id.outputs.job_id }}.json
+    #     else
+    #       ./benchmark/compile_and_run.sh ~/testify/ll-sw/${{ matrix.build.dir }}/mlir_reports/ttir_out.mlir ${{ steps.strings.outputs.perf_report_path }}/benchmark_${{ matrix.build.project }}_e2e_${{ matrix.build.name }}_${{ matrix.build.bs }}_${{ matrix.build.lp }}_.json || true # ${{ steps.fetch-job-id.outputs.job_id }}.json || true
+    #     fi
 
     # - name: Upload Perf Report
     #   uses: actions/upload-artifact@v4
